# Churn Analysis
[Medium link](https://medium.com/@pushkarmandot/build-your-first-deep-learning-neural-network-model-using-keras-in-python-a90b5864116d)
## Business Problem:
Our basic aim is to predict customer churn for a certain bank i.e. which customer is going to leave this bank service. Dataset is small(for learning purpose) and contains 10000 rows with 14 columns. I am not explaining data in detail as dataset is self explanatory

In [2]:
import numpy as np
#import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
#dataset.Geography.unique()

In [6]:
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:, 13].values

In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [10]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [11]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

D:\Environments\OpenCVAndAll\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
D:\Environments\OpenCVAndAll\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [12]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [13]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [14]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [15]:
#Initializing Neural Network
classifier = Sequential()

W0814 10:53:29.764300 24476 deprecation_wrapper.py:119] From D:\Environments\OpenCVAndAll\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [16]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

D:\Environments\OpenCVAndAll\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  
W0814 10:53:40.882738 24476 deprecation_wrapper.py:119] From D:\Environments\OpenCVAndAll\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0814 10:53:40.918737 24476 deprecation_wrapper.py:119] From D:\Environments\OpenCVAndAll\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

D:\Environments\OpenCVAndAll\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
D:\Environments\OpenCVAndAll\lib\site-packages\ipykernel_launcher.py:6: UserWarning: U

In [17]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

W0814 10:53:53.547525 24476 deprecation_wrapper.py:119] From D:\Environments\OpenCVAndAll\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0814 10:53:53.579521 24476 deprecation_wrapper.py:119] From D:\Environments\OpenCVAndAll\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0814 10:53:53.583487 24476 deprecation.py:323] From D:\Environments\OpenCVAndAll\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [18]:
# Fitting our model 
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

D:\Environments\OpenCVAndAll\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  
W0814 10:54:07.874919 24476 deprecation_wrapper.py:119] From D:\Environments\OpenCVAndAll\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.5733 - acc: 0.7800
Epoch 2/100
8000/8000 [==============================] - 1s 99us/step - loss: 0.5316 - acc: 0.7937
Epoch 3/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.5237 - acc: 0.7937
Epoch 4/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.5164 - acc: 0.7937
Epoch 5/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.5131 - acc: 0.7937
Epoch 6/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.5115 - acc: 0.7937
Epoch 7/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.5069 - acc: 0.7937
Epoch 8/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.5052 - acc: 0.7937
Epoch 9/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.5057 - acc: 0.7937
Epoch 10/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.5035 - acc: 0.7937
Epoch 

8000/8000 [==============================] - 1s 91us/step - loss: 0.5027 - acc: 0.7937
Epoch 83/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.5021 - acc: 0.7937
Epoch 84/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.5024 - acc: 0.7937
Epoch 85/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.5024 - acc: 0.7937
Epoch 86/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.5022 - acc: 0.7937
Epoch 87/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.5022 - acc: 0.7937
Epoch 88/100
8000/8000 [==============================] - 1s 82us/step - loss: 0.5024 - acc: 0.7937
Epoch 89/100
8000/8000 [==============================] - 1s 85us/step - loss: 0.5022 - acc: 0.7937
Epoch 90/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.5022 - acc: 0.7937
Epoch 91/100
8000/8000 [==============================] - 1s 82us/step - loss: 0.5022 - acc: 0.7937
Epoch 92/100


In [19]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [20]:
y_pred

array([[0.24245358],
       [0.24245358],
       [0.24245358],
       ...,
       [0.14900431],
       [0.24245358],
       [0.24245358]], dtype=float32)

In [21]:
y_pred = (y_pred > 0.5)

In [22]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [23]:
# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [24]:
cm

array([[1613,    0],
       [ 387,    0]], dtype=int64)